name: fixitnow
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-245.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rive: ^0.9.1
  flutter_svg: ^2.0.4
  http: ^0.13.6
  #Internal phone input
  intl_phone_number_input: ^0.7.3+1

  otp_text_field: ^1.1.3

  #Firebase
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  firebase_core_web: ^2.0.1
  cloud_firestore_web: ^3.0.3
  firebase_storage: ^11.0.3
  cloud_firestore: ^4.0.3  

  #GeoLocation
  geolocator: ^8.2.1
  geocoding: ^2.0.4
  google_maps_flutter: ^2.1.4

  #Utils plugins
  google_fonts: ^4.0.4
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.5.0

  #flutter_settings_screens: ^0.2.0
  shared_preferences: ^2.0.8
  datetime_picker_formfield: ^2.0.0
  fluttertoast: ^8.0.8
  flutter_launcher_icons: ^0.9.2
  pixel_perfect: ^1.1.1
  flutter_rating_bar: ^4.0.0
  dropdown_button2: ^1.4.0

  #Flutter Secure storage
  #flutter_secure_storage: ^5.0.2
  #flutter_secure_storage_web: ^1.0.2
  
  #Image
  image_picker: ^0.8.4+4
  image_cropper: ^1.4.1
  camera: ^0.10.0+3
  path_provider: ^2.0.11
  path:
  intl: ^0.17.0
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  mobx: ^2.2.1 
  flutter_mobx: ^2.1.0+1
  photo_manager: ^2.8.0
  flutter_storage_path: ^1.0.4

  auto_size_text: ^3.0.0
  json_annotation: ^4.8.0
  searchfield: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0
  json_serializable: ^6.6.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/avaters/
    - assets/Backgrounds/
    - assets/icons/
    - assets/RiveAssets/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Intel
      fonts:
        - asset: assets/Fonts/Inter-Regular.ttf
        - asset: assets/Fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700
